name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [windows-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Build artifact
        run: |
          pip install -r requirements.txt pyinstaller
          pyinstaller --onefile --noconsole --name heimerdinger --icon=icon.png --add-data "icon.png:." main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: heimerdinger
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: heimerdinger
    - name: Push to release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        artifacts: heimerdinger.exe